services:
  db:
    image: postgres:16.14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - app-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      timeout: 2s
      retries: 10
  dex:
    image: dexidp/dex:v2.45.1-alpine
    ports:
      - "5556:5556"
    volumes:
      - ./services/mock-auth/config.yaml:/etc/dex/config.yaml
    command: ["dex", "serve", "/etc/dex/config.yaml"]
  mail:
    image: axllent/mailpit:v1.30
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  mock-ses:
    image: ghcr.io/domdomegg/aws-ses-v2-local
    restart: unless-stopped
    ports:
      - 8005:8005
    environment:
      - SMTP_TRANSPORT={"host":"mail","port":1025,"secure":false}
  app:
    image: app:local
    build: .
    read_only: true
    restart: always
    env_file:
      - ./apps/backend/.env.development
    environment:
      - DB_HOST=db
      - APP_DOMAIN=http://localhost:8080
      - OAUTH_CLIENT_CALLBACK_URL=http://localhost:8080/api/v1/auth/oauth/redirect
      - PASSKEY_ORIGIN="http://localhost:8080"
    ports:
      - 8080:8080
    depends_on:
      - db
    extra_hosts:
      - "localhost:host-gateway"
    profiles:
      - prod-local
    

volumes:
  app-pg-data: