# config.yaml
issuer: http://localhost:5556/dex
storage:
  type: memory
web:
  http: 0.0.0.0:5556
oauth2:
  skipApprovalScreen: true
staticClients:
  - id: full-stack-app
    redirectURIs:
      - 'http://localhost:3000/api/v1/auth/oauth/redirect'
      - 'http://localhost:8080/api/v1/auth/oauth/redirect'
    name: 'Full Stack App'
    secret: auth-client-secret
    public: true
enablePasswordDB: true
staticPasswords:
  - email: "u1@test.com"
    # Password: u1
    hash: "$2a$12$OsK3TQiXpI.Z1wwVJRC25OUUz480oCkyze/ZDmM97YyFQUitfKLV6"
    username: "u1"
    name: "User 1"
  - email: "u2@test.com"
    # Password: u2
    hash: "$2a$12$9C3s0lYMIS7QdsQk.Z8foeHz21.LBHN9Mf1xaqSIHDm.vRO.9/DZi"
    username: "u2"
    name: "User 2"